[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 1000000
via_ir = true

# Base RPC for forking
[rpc_endpoints]
base = "https://mainnet.base.org"
# Or use your own RPC: base = "${BASE_RPC_URL}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
